export const CREATE_POST = 'CREATE_POST'
export const DELETE_POST = 'DELETE_POST'
export const GET_ALL_POSTS = 'GET_ALL_POSTS'
export const EDIT_POST = 'EDIT_POST'
export const UP_VOTE = 'UP_VOTE'
export const DOWN_VOTE = 'DOWN_VOTE'
export const SORT_BY_TIME = 'SORT_BY_TIME'
export const SORT_BY_VOTE = 'SORT_BY_VOTE'

export const GET_ALL_CATEGORIES = 'GET_ALL_CATEGORIES'

export const UP_VOTE_COMMENT = 'UP_VOTE_COMMENT'
export const DOWN_VOTE_COMMENT = 'DOWN_VOTE_COMMENT'

export const GET_ALL_COMMENTS = 'GET_ALL_COMMENTS'
export const DELETE_COMMENT = 'DELETE_COMMENT'
export const EDIT_COMMENT = 'EDIT_COMMENT'
export const CREATE_COMMENT = 'CREATE_COMMENT'